sudo: required
services:
  - docker

before_install:
  - docker build -t jlxc106/docker_with_react -f Dockerfile.dev .


script:
  - docker run jlxc106/docker_with_react npm run test  -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker_with_react"
  env: "DockerWithReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-984635072188"
  bucket_path: "docker_with_react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"